# Generated by Django 5.0.1 on 2024-02-22 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchnumber', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('batchcost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('batchdate', models.DateField(auto_now_add=True)),
                ('manufacturedate', models.DateField(auto_now=True)),
                ('expirydate', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
