# Generated by Django 5.0.1 on 2024-02-25 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product_mrp_alter_product_weight_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=6)),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
            ],
        ),
    ]
